#!/bin/bash
#
# Streams 24 kHz stereo from the C920 camera. At this rate the Beaglebone
# CPU load will stay at acceptable level.
#
# Otherwise one can use raw audio through TCP connection which uses low CPU
# but high bitrate.
#
# NB: Check the audio device number before running the script!
#

usage ()
{
    echo "Usage:  audio-server <host_ip> <host_port>"
}


if [ $# -ne 2 ]; then
    usage
    exit 0
fi

echo "Starting audio streaming server to $1:$2"

## Vorbis encoded audio
#gst-launch-1.0 -v -e alsasrc device="plughw:0" ! audio/x-raw,format=\(string\)S16LE,rate=24000,channels=2 ! audioconvert ! vorbisenc ! rtpvorbispay ! udpsink host=$1 port=$2

## Raw audio via tcp (~ 1 Mbps)
while true; do
    gst-launch-1.0 -v -e alsasrc device="plughw:0" ! audio/x-raw,format=\(string\)S16LE,rate=48000,channels=1 ! tcpclientsink host=$1 port=$2 sync=true
    sleep 5
done

