#!/bin/bash

bld="TARGET"

if [ $# -eq 1 ] && [ "$1" == "host" ]; then
    bld="HOST"
fi

if [ $bld == "HOST" ]; then
    gcc -O2 -Wall `pkg-config --cflags --libs libv4l2` capture.c -o capture
else
    gcc -O2 -Wall -marm -mfloat-abi=softfp `pkg-config --cflags --libs libv4l2` capture.c -o capture
fi

